-- Migração: Módulo de Cotações
-- Caminho: supabase/migrations/20260616091000_create_cotacoes_table.sql

-- =========================================================================
-- 1. TABELA PRINCIPAL: public.cotacoes
-- =========================================================================
create table if not exists public.cotacoes (
  id uuid not null default gen_random_uuid(),
  numero integer generated by default as identity,
  criado_em timestamp with time zone null default timezone('utc'::text, now()),
  atualizado_em timestamp with time zone null default timezone('utc'::text, now()),
  excluido_em timestamp with time zone null, -- Soft Delete
  
  cliente_id uuid null references public.clientes(id) on delete set null,
  vendedor_id uuid null references public.usuarios(id) on delete set null,
  criado_por uuid null references auth.users(id) on delete set null,
  
  cnpj text not null,
  razao_social text not null,
  prazos integer[] not null, -- ex: array[60, 72, 84]
  estimativa_rodagem_km numeric(10,2) not null,
  tipo_placa text not null check (tipo_placa in ('Comum', 'ANTT')),
  descricao text null,
  detalhamento_ativo boolean not null default false,
  status text not null default 'Em avaliação' check (status in ('Em avaliação', 'Em orçamento', 'Completo')),
  
  constraint cotacoes_pkey primary key (id)
);

-- RLS
alter table public.cotacoes enable row level security;

-- Policies RLS
create policy "Permitir leitura de cotacoes para autenticados"
  on public.cotacoes for select to authenticated using (excluido_em is null);

create policy "Permitir insercao de cotacoes para autenticados"
  on public.cotacoes for insert to authenticated with check (true);

create policy "Permitir edicao de cotacoes para criadores ou administradores"
  on public.cotacoes for update to authenticated using (
    criado_por = auth.uid() or 
    exists (
      select 1 from public.usuarios 
      where usuarios.usuario_id = auth.uid() 
      and usuarios.perfil = 'administrador'
    )
  );

-- =========================================================================
-- 2. TABELA: public.cotacao_itens (Itens detalhados)
-- =========================================================================
create table if not exists public.cotacao_itens (
  id uuid not null default gen_random_uuid(),
  cotacao_id uuid not null references public.cotacoes(id) on delete cascade,
  criado_em timestamp with time zone null default timezone('utc'::text, now()),
  atualizado_em timestamp with time zone null default timezone('utc'::text, now()),
  
  tipo_item text not null check (tipo_item in ('caminhao', 'implemento')),
  caminhao_id uuid null references public.caminhoes(id) on delete set null,
  categoria_id uuid null references public.categorias(id) on delete set null,
  opcoes_selecionadas jsonb null, -- ex: [{ "atributo_id": "...", "opcao_id": "..." }]
  quantidade integer not null default 1,
  observacao text null,
  
  constraint cotacao_itens_pkey primary key (id)
);

-- RLS
alter table public.cotacao_itens enable row level security;

create policy "Permitir leitura de itens para autenticados"
  on public.cotacao_itens for select to authenticated using (true);

create policy "Permitir insercao de itens para autenticados"
  on public.cotacao_itens for insert to authenticated with check (true);

create policy "Permitir edicao de itens para autenticados"
  on public.cotacao_itens for update to authenticated using (true);

create policy "Permitir delecao de itens para autenticados"
  on public.cotacao_itens for delete to authenticated using (true);


-- =========================================================================
-- 3. TABELA: public.cotacao_anexos (Arquivos associados)
-- =========================================================================
create table if not exists public.cotacao_anexos (
  id uuid not null default gen_random_uuid(),
  cotacao_id uuid not null references public.cotacoes(id) on delete cascade,
  criado_por uuid null references auth.users(id) on delete set null,
  criado_em timestamp with time zone null default timezone('utc'::text, now()),
  
  arquivo_nome text not null,
  arquivo_url text not null,
  arquivo_path text not null,
  mime_type text not null,
  tamanho_bytes bigint not null,
  
  constraint cotacao_anexos_pkey primary key (id)
);

-- RLS
alter table public.cotacao_anexos enable row level security;

create policy "Permitir leitura de anexos para autenticados"
  on public.cotacao_anexos for select to authenticated using (true);

create policy "Permitir insercao de anexos para autenticados"
  on public.cotacao_anexos for insert to authenticated with check (true);

create policy "Permitir delecao de anexos para autenticados"
  on public.cotacao_anexos for delete to authenticated using (true);


-- =========================================================================
-- 4. TABELA: public.cotacao_comentarios (Notas/Comentários)
-- =========================================================================
create table if not exists public.cotacao_comentarios (
  id uuid not null default gen_random_uuid(),
  cotacao_id uuid not null references public.cotacoes(id) on delete cascade,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  criado_em timestamp with time zone null default timezone('utc'::text, now()),
  
  mensagem text not null,
  
  constraint cotacao_comentarios_pkey primary key (id)
);

-- RLS
alter table public.cotacao_comentarios enable row level security;

create policy "Permitir leitura de comentarios para autenticados"
  on public.cotacao_comentarios for select to authenticated using (true);

create policy "Permitir insercao de comentarios para autenticados"
  on public.cotacao_comentarios for insert to authenticated with check (true);

create policy "Permitir delecao de comentarios apenas para criadores"
  on public.cotacao_comentarios for delete to authenticated using (
    exists (
      select 1 from public.usuarios 
      where usuarios.id = usuario_id 
      and usuarios.usuario_id = auth.uid()
    )
  );


-- =========================================================================
-- 5. POPULAR DADOS DE TESTE (CONFORME SISTEMA ANTIGO)
-- =========================================================================
-- Nota: Associamos os IDs dos usuários 'Pedro Pelosini' e 'Samuel Victor' e cliente 'GRI' cadastrados
insert into public.cotacoes (
  numero,
  cnpj,
  razao_social,
  cliente_id,
  vendedor_id,
  prazos,
  estimativa_rodagem_km,
  tipo_placa,
  detalhamento_ativo,
  status,
  descricao
) values
  (
    4,
    '',
    '',
    null,
    'd6b8d3dc-3948-415a-b355-c6883bdb25c2', -- Pedro Pelosini
    array[60, 72],
    5000.00,
    'Comum',
    false,
    'Em avaliação',
    'Cotação preliminar para caminhão Constellation.'
  ),
  (
    5,
    '51.903.449/0001-09',
    'GRI - GERENCIAMENTO DE RESÍDUOS INDUSTRIAIS S.A.',
    'a62bf8e9-7cc7-45a0-a5c5-1c9f222a7cb1', -- GRI Cliente
    'd6b8d3dc-3948-415a-b355-c6883bdb25c2', -- Pedro Pelosini
    array[60, 72, 84],
    4500.00,
    'Comum',
    false,
    'Em avaliação',
    'Locação de caminhões para coleta.'
  ),
  (
    6,
    '51.903.449/0001-08',
    'GRI - GERENCIAMENTO DE RESÍDUOS INDUSTRIAIS S.A.',
    null, -- Cliente não pré-cadastrado no banco
    '46df306d-2ae3-4af2-afb1-b96129a06742', -- Samuel Victor (substituindo Pedro Vendedor)
    array[60, 72, 84],
    3000.00,
    'ANTT',
    false,
    'Em avaliação',
    'Locação com placa ANTT severa.'
  );
